/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import classes.DataManager;
import javax.swing.JOptionPane;

/**
 *
 * @author JebGy
 */
public class MainView extends javax.swing.JPanel {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputs2 = new componentes.Inputs();
        inputs1 = new componentes.Inputs();
        jLabel10 = new javax.swing.JLabel();
        txt_fun = new componentes.Inputs();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        lbl_Fun = new javax.swing.JLabel();
        btn_Solve = new componentes.ButtonPanel();
        jLabel1 = new javax.swing.JLabel();
        inputs3 = new componentes.Inputs();
        btn_Save = new componentes.ButtonPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(44, 44, 44));
        setPreferredSize(new java.awt.Dimension(779, 397));

        inputs2.setColumns(2);
        inputs2.setForeground(new java.awt.Color(255, 255, 255));
        inputs2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputs2.setToolTipText("Example for Y: 2;5");
        inputs2.setCaretColor(new java.awt.Color(255, 255, 255));
        inputs2.setFont(new java.awt.Font("Lato Light", 0, 18)); // NOI18N

        inputs1.setColumns(2);
        inputs1.setForeground(new java.awt.Color(255, 255, 255));
        inputs1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputs1.setToolTipText("Example for X: 2;5");
        inputs1.setCaretColor(new java.awt.Color(255, 255, 255));
        inputs1.setFont(new java.awt.Font("Lato Light", 0, 18)); // NOI18N

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Lato Light", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Write the intervals here:");

        txt_fun.setColumns(2);
        txt_fun.setForeground(new java.awt.Color(255, 255, 255));
        txt_fun.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fun.setToolTipText("Example:    x*y+6z**2");
        txt_fun.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_fun.setFont(new java.awt.Font("Lato Light", 0, 18)); // NOI18N

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Lato Light", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Write the function:");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Lato Light", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Your function is:");

        lbl_Fun.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Fun.setFont(new java.awt.Font("Lato Light", 0, 48)); // NOI18N
        lbl_Fun.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Fun.setText("∫");

        btn_Solve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SolveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SolveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SolveMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lato Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SOLVE");

        javax.swing.GroupLayout btn_SolveLayout = new javax.swing.GroupLayout(btn_Solve);
        btn_Solve.setLayout(btn_SolveLayout);
        btn_SolveLayout.setHorizontalGroup(
            btn_SolveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_SolveLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        btn_SolveLayout.setVerticalGroup(
            btn_SolveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_SolveLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        inputs3.setColumns(2);
        inputs3.setForeground(new java.awt.Color(255, 255, 255));
        inputs3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputs3.setToolTipText("Example for Y: 2;5");
        inputs3.setCaretColor(new java.awt.Color(255, 255, 255));
        inputs3.setFont(new java.awt.Font("Lato Light", 0, 18)); // NOI18N

        btn_Save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SaveMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lato Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Save");

        javax.swing.GroupLayout btn_SaveLayout = new javax.swing.GroupLayout(btn_Save);
        btn_Save.setLayout(btn_SaveLayout);
        btn_SaveLayout.setHorizontalGroup(
            btn_SaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_SaveLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_SaveLayout.setVerticalGroup(
            btn_SaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_SaveLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");

        jLabel4.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Z");

        jLabel5.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Y");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Save, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputs2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(inputs1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(inputs3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(txt_fun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(jLabel12))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(46, 46, 46)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_Fun, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addComponent(btn_Solve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputs1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputs2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputs3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_fun, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_Fun, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(btn_Solve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SolveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SolveMouseClicked
        try {
            DataManager dm = new DataManager();
            dm.runners();
            Thread.sleep(2000);
            jTextArea1.setText(dm.readData());
        } catch (InterruptedException ex) {
            JOptionPane.showMessageDialog(null, "Error al resolver");
        }
    }//GEN-LAST:event_btn_SolveMouseClicked

    private void btn_SolveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SolveMouseEntered
        btn_Solve.setCr(119);
        btn_Solve.setCrg(208);
        btn_Solve.setCrgb(124);
    }//GEN-LAST:event_btn_SolveMouseEntered

    private void btn_SolveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SolveMouseExited
        btn_Solve.setCr(44);
        btn_Solve.setCrg(44);
        btn_Solve.setCrgb(44);
    }//GEN-LAST:event_btn_SolveMouseExited

    private void btn_SaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SaveMouseEntered
        btn_Save.setCr(109);
        btn_Save.setCrg(208);
        btn_Save.setCrgb(124);
    }//GEN-LAST:event_btn_SaveMouseEntered

    private void btn_SaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SaveMouseExited
        btn_Save.setCr(44);
        btn_Save.setCrg(44);
        btn_Save.setCrgb(44);
    }//GEN-LAST:event_btn_SaveMouseExited

    private void btn_SaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SaveMouseClicked
        DataManager dm = new DataManager();
        
        if ("".equals(inputs2.getText()) && "".equals(inputs3.getText())) {
            dm.setFormula(txt_fun.getText());
            dm.setInterval(inputs1.getText());
            lbl_Fun.setText("∫" + txt_fun.getText());
            dm.writeData(dm.getFormula(), dm.getInterval());
            JOptionPane.showMessageDialog(null, "Saved");
            
        } else if ("".equals(inputs2.getText())) {
            dm.setFormula(txt_fun.getText());
            dm.setInterval(inputs1.getText() + "," + inputs3.getText());
            lbl_Fun.setText("∫∫"+txt_fun.getText());
            dm.writeData(dm.getFormula(), dm.getInterval());
            JOptionPane.showMessageDialog(null, "Saved");
            
        } else {
            dm.setFormula(txt_fun.getText());
            dm.setInterval(inputs1.getText() + "," + inputs2.getText() + "," + inputs3.getText());
            lbl_Fun.setText("∫∫∫" + txt_fun.getText());
            dm.writeData(dm.getFormula(), dm.getInterval());
            JOptionPane.showMessageDialog(null, "Saved");
        }

    }//GEN-LAST:event_btn_SaveMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.ButtonPanel btn_Save;
    private componentes.ButtonPanel btn_Solve;
    private componentes.Inputs inputs1;
    private componentes.Inputs inputs2;
    private componentes.Inputs inputs3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_Fun;
    private componentes.Inputs txt_fun;
    // End of variables declaration//GEN-END:variables
}
